const icon=id=>`https://maplestory.io/api/GMS/83/item/${id}/icon`;
let items=[],itemPage=1;
const PAGE_SIZE=24;
const safe=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const label=value=>value?value.charAt(0).toUpperCase()+value.slice(1):'Item';
function itemMeta(item){return `${item.subCategory||item.category||label(item.type)}${item.requiredLevel?` · Level ${item.requiredLevel}`:''}`;}
const mobIcon=id=>`https://maplestory.io/api/GMS/83/mob/${id}/icon`;
let monsters=[],monsterPage=1;
const MONSTER_PAGE_SIZE=24;
const expToNext=[15,34,57,92,135,372,560,840,1242,1716,2360,3216,4200,5460,7050,8840,11040,13716,16680,20216,24402,28980,34320,40512,47216,54900,63666,73080,83720,95700,108480,122760,138666,155540,174216,194832,216600,240500,266682,294216,324240,356916,391160,428280,468450,510420,555680,604416,655200,709716,748608,789631,832902,878545,926689,977471,1031036,1087536,1147132,1209904,1276301,1346242,1419929,1497544,1579284,1665351,1755965,1851353,1951755,2057421,2168603,2285568,2408594,2537968,2673990,2816972,2967236,3125118,3280966,3445142,3618024,3800007,3991500,4192930,4404820,4627614,4861766,5107740,5366016,5637085,5921449,6219621,6532128,6859500,7192300,7541082,7906420,8288900,8689110,9107660];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function itemCard(item){const description=item.desc||`${item.subCategory||item.category||label(item.type)} from the GMS v83 item archive.`;return `<button class="item-card" type="button" data-item-id="${item.id}" aria-label="Open ${safe(item.name)} details"><span class="item-icon"><img src="${icon(item.id)}" alt="" loading="lazy"></span><span><span class="item-meta">${safe(itemMeta(item))}</span><h3>${safe(item.name)}</h3><p>${safe(description)}</p></span></button>`}
function openItem(id){const item=items.find(x=>x.id===id);if(!item)return;const jobs=item.requiredJobs?.length?item.requiredJobs.join(', '):'Any';const gender=item.requiredGender===0?'Male':item.requiredGender===1?'Female':'Any';$('#dialog-image').src=icon(item.id);$('#dialog-image').alt=`${item.name} item artwork`;$('#dialog-meta').textContent=`${itemMeta(item)} · ID ${item.id}`;$('#item-dialog-title').textContent=item.name;$('#dialog-description').textContent=item.desc||`${item.subCategory||item.category||label(item.type)} from the GMS v83 item archive.`;$('#dialog-stats').innerHTML=[["Required level",item.requiredLevel||'None'],['Jobs',jobs],['Gender',gender]].map(([key,value])=>`<div class="dialog-stat"><span>${safe(key)}</span><strong>${safe(value)}</strong></div>`).join('');$('#dialog-source').textContent=`Catalogued under ${item.category||label(item.type)} → ${item.subCategory||'General'}. Exact quest, shop, and drop sources will be added as the source database is reviewed.`;$('#dialog-monsters').innerHTML='<span>Drop data pending review</span>';$('#item-dialog').showModal();}
function renderPagination(totalPages){if(totalPages<=1){$('#item-pagination').innerHTML='';return;}const start=Math.max(1,Math.min(itemPage-2,totalPages-4)),end=Math.min(totalPages,start+4),pages=[];for(let page=start;page<=end;page++)pages.push(`<button type="button" data-page="${page}" ${page===itemPage?'aria-current="page"':''}>${page}</button>`);$('#item-pagination').innerHTML=`<button type="button" data-page="${Math.max(1,itemPage-1)}" ${itemPage===1?'disabled':''}>← Previous</button>${pages.join('')}<button type="button" data-page="${Math.min(totalPages,itemPage+1)}" ${itemPage===totalPages?'disabled':''}>Next →</button>`;$$('[data-page]').forEach(button=>button.onclick=()=>{itemPage=+button.dataset.page;renderItems();$('#items-panel').scrollIntoView({behavior:'smooth',block:'start'});});}
function renderItems(){const q=$('#item-search').value.trim().toLowerCase(),active=$('[data-item-filter].active').dataset.itemFilter;const found=items.filter(x=>(active==='all'||x.type===active)&&`${x.name} ${x.id} ${x.category} ${x.subCategory} ${x.desc} ${x.requiredLevel}`.toLowerCase().includes(q)),totalPages=Math.max(1,Math.ceil(found.length/PAGE_SIZE));itemPage=Math.min(itemPage,totalPages);const visible=found.slice((itemPage-1)*PAGE_SIZE,itemPage*PAGE_SIZE);$('#item-grid').innerHTML=visible.map(itemCard).join('')||'<p>No items found. Try another search.</p>';$('#item-count').textContent=`${found.length.toLocaleString()} ITEM${found.length===1?'':'S'} FOUND · PAGE ${itemPage} OF ${totalPages}`;renderPagination(totalPages);$$('[data-item-id]').forEach(card=>card.onclick=()=>openItem(+card.dataset.itemId));}
async function loadItems(){try{const response=await fetch('item-data.json');if(!response.ok)throw new Error('Catalog unavailable');items=(await response.json()).filter(item=>item.category!=='Character');const featured=[1092008,1302013,1302000,1322005,1332005,1382002,1402001,1412001,1422001,1432002,1442001,1452002,1462001,1472000,1002026,1050018,1082002];items.sort((a,b)=>{const ai=featured.indexOf(a.id),bi=featured.indexOf(b.id);if(ai!==-1||bi!==-1)return(ai===-1?999:ai)-(bi===-1?999:bi);return(a.requiredLevel||0)-(b.requiredLevel||0)||a.name.localeCompare(b.name);});$$('[data-item-filter]').forEach(button=>{const category=button.dataset.itemFilter,count=category==='all'?items.length:items.filter(item=>item.type===category).length;button.textContent=`${button.textContent.replace(/\s[\d,]+$/,'')} ${count.toLocaleString()}`;});renderItems();}catch(error){$('#item-count').textContent='ITEM CATALOG COULD NOT BE LOADED';$('#item-grid').innerHTML='<p>Please refresh the page to try again.</p>';}}
function levelMatch(level,range){if(range==='all')return true;if(range.endsWith('+'))return level>=Number(range.slice(0,-1));const [a,b]=range.split('-').map(Number);return level>=a&&level<=b;}
function monsterCard(monster){const flags=[monster.isBoss?'Boss':'',monster.isUndead?'Undead':''].filter(Boolean).join(' · ')||'Field monster';return `<button class="monster-card" type="button" data-monster-id="${monster.id}" aria-label="Open ${safe(monster.name)} details"><span class="monster-art"><img src="${mobIcon(monster.id)}" alt="" loading="lazy"></span><span class="monster-card-copy"><span class="item-meta">${safe(flags)} · ID ${monster.id}</span><h3>${safe(monster.name)}</h3><span class="monster-numbers"><span><small>LV.</small>${monster.level}</span><span><small>HP</small>${(monster.hp||0).toLocaleString()}</span><span><small>EXP</small>${(monster.exp||0).toLocaleString()}</span></span></span></button>`;}
function openMonster(id){const monster=monsters.find(x=>x.id===id);if(!monster)return;$('#monster-dialog-image').src=mobIcon(monster.id);$('#monster-dialog-image').alt=`${monster.name} monster artwork`;$('#monster-dialog-meta').textContent=`Level ${monster.level} · ID ${monster.id}${monster.isBoss?' · Boss':''}${monster.isUndead?' · Undead':''}`;$('#monster-dialog-title').textContent=monster.name;$('#monster-dialog-description').textContent=(monster.description||'No description is available for this monster.').replace(/\\n/g,' ').replace(/\s+/g,' ').trim();const stats=[['HP',(monster.hp||0).toLocaleString()],['MP',(monster.mp||0).toLocaleString()],['EXP',(monster.exp||0).toLocaleString()],['Physical damage',(monster.physicalDamage||0).toLocaleString()],['Magic damage',(monster.magicDamage||0).toLocaleString()],['Accuracy',(monster.accuracy||0).toLocaleString()],['Physical defense',(monster.physicalDefense||0).toLocaleString()],['Magic defense',(monster.magicDefense||0).toLocaleString()],['Avoidability',(monster.evasion||0).toLocaleString()]];$('#monster-dialog-stats').innerHTML=stats.map(([key,value])=>`<div class="dialog-stat"><span>${key}</span><strong>${value}</strong></div>`).join('');$('#monster-dialog-locations').textContent=monster.foundAt?.length?`${monster.foundAt.length} map IDs recorded: ${monster.foundAt.slice(0,12).join(', ')}${monster.foundAt.length>12?'…':''}`:'No recorded map locations in this source.';$('#monster-dialog').showModal();}
function renderMonsterPagination(totalPages){if(totalPages<=1){$('#monster-pagination').innerHTML='';return;}const start=Math.max(1,Math.min(monsterPage-2,totalPages-4)),end=Math.min(totalPages,start+4),pages=[];for(let page=start;page<=end;page++)pages.push(`<button type="button" data-monster-page="${page}" ${page===monsterPage?'aria-current="page"':''}>${page}</button>`);$('#monster-pagination').innerHTML=`<button type="button" data-monster-page="${Math.max(1,monsterPage-1)}" ${monsterPage===1?'disabled':''}>← Previous</button>${pages.join('')}<button type="button" data-monster-page="${Math.min(totalPages,monsterPage+1)}" ${monsterPage===totalPages?'disabled':''}>Next →</button>`;$$('[data-monster-page]').forEach(button=>button.onclick=()=>{monsterPage=+button.dataset.monsterPage;renderMonsters();$('#monsters-panel').scrollIntoView({behavior:'smooth',block:'start'});});}
function renderMonsters(){const q=$('#monster-search').value.trim().toLowerCase(),range=$('#monster-level').value,filter=$('[data-monster-filter].active').dataset.monsterFilter;const found=monsters.filter(monster=>levelMatch(monster.level,range)&&(filter==='all'||filter==='boss'&&monster.isBoss||filter==='undead'&&monster.isUndead)&&`${monster.name} ${monster.id} ${monster.description}`.toLowerCase().includes(q)),totalPages=Math.max(1,Math.ceil(found.length/MONSTER_PAGE_SIZE));monsterPage=Math.min(monsterPage,totalPages);const visible=found.slice((monsterPage-1)*MONSTER_PAGE_SIZE,monsterPage*MONSTER_PAGE_SIZE);$('#monster-rows').innerHTML=visible.map(monsterCard).join('')||'<p>No monsters found. Try another search or level range.</p>';$('#monster-count').textContent=`${found.length.toLocaleString()} MONSTER${found.length===1?'':'S'} FOUND · PAGE ${monsterPage} OF ${totalPages}`;renderMonsterPagination(totalPages);$$('[data-monster-id]').forEach(card=>card.onclick=()=>openMonster(+card.dataset.monsterId));}
async function loadMonsters(){try{const response=await fetch('monster-data.json');if(!response.ok)throw new Error('Bestiary unavailable');monsters=(await response.json()).filter(monster=>monster.level&&monster.name!=='???');const featured=[100100,100101,120100,130101,130100,210100,1210100,1210102,1210101,1110100,2110200,2230101,2230102,3230101,9300003,6130101];monsters.sort((a,b)=>{const ai=featured.indexOf(a.id),bi=featured.indexOf(b.id);if(ai!==-1||bi!==-1)return(ai===-1?999:ai)-(bi===-1?999:bi);return a.level-b.level||a.name.localeCompare(b.name);});$$('[data-monster-filter]').forEach(button=>{const filter=button.dataset.monsterFilter,count=filter==='all'?monsters.length:monsters.filter(monster=>filter==='boss'?monster.isBoss:monster.isUndead).length;button.textContent=`${button.textContent.replace(/\s[\d,]+$/,'')} ${count.toLocaleString()}`;});$('#training-monster').innerHTML='<option value="">No monster selected</option>'+monsters.filter(monster=>monster.exp>0).map(monster=>`<option value="${safe(monster.name)}">${safe(monster.name)} · Lv. ${monster.level} · ${monster.exp.toLocaleString()} EXP</option>`).join('');renderMonsters();calculate();}catch(error){$('#monster-count').textContent='MONSTER CATALOG COULD NOT BE LOADED';$('#monster-rows').innerHTML='<p>Please refresh the page to try again.</p>';}}
function cumulative(level){let total=0;for(let i=1;i<level;i++)total+=expToNext[i-1]||expToNext.at(-1);return total;}
function formatTime(hours){if(!Number.isFinite(hours)||hours<=0)return'Add a rate';if(hours<1)return`${Math.ceil(hours*60)} min`;return`${hours.toFixed(hours<10?1:0)} hr`;}
function calculate(){const current=Math.max(1,Math.min(99,+$('#current-level').value||1)),target=Math.max(current+1,Math.min(100,+$('#target-level').value||current+1)),inside=Math.max(0,+$('#current-exp').value||0),remaining=Math.max(0,cumulative(target)-cumulative(current)-inside),monster=monsters.find(x=>x.name===$('#training-monster').value),rate=Math.max(0,+$('#exp-hour').value||0),levelExp=expToNext[current-1]||1;$('#level-route').textContent=`Level ${current} to ${target}`;$('#exp-needed').textContent=remaining.toLocaleString();$('#levels-to-go').textContent=target-current;$('#kills-needed').textContent=monster?Math.ceil(remaining/monster.exp).toLocaleString():'Add a monster';$('#time-needed').textContent=formatTime(remaining/rate);$('#level-progress').style.width=`${Math.min(100,inside/levelExp*100)}%`;}
$$('[data-tool]').forEach(button=>button.onclick=()=>{$$('[data-tool]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));$$('.tool-panel').forEach(p=>p.hidden=p.id!==`${button.dataset.tool}-panel`);history.replaceState(null,'',`#${button.dataset.tool}`);});
$$('[data-item-filter]').forEach(b=>b.onclick=()=>{$$('[data-item-filter]').forEach(x=>x.classList.toggle('active',x===b));itemPage=1;renderItems();});
$('#item-search').addEventListener('input',()=>{itemPage=1;renderItems();});$('#monster-search').addEventListener('input',()=>{monsterPage=1;renderMonsters();});$('#monster-level').addEventListener('change',()=>{monsterPage=1;renderMonsters();});$$('[data-monster-filter]').forEach(button=>button.onclick=()=>{$$('[data-monster-filter]').forEach(x=>x.classList.toggle('active',x===button));monsterPage=1;renderMonsters();});$('#exp-form').addEventListener('input',calculate);
$('#dialog-close').onclick=()=>$('#item-dialog').close();
$('#item-dialog').onclick=e=>{if(e.target===$('#item-dialog'))$('#item-dialog').close();};
$('#monster-dialog-close').onclick=()=>$('#monster-dialog').close();
$('#monster-dialog').onclick=e=>{if(e.target===$('#monster-dialog'))$('#monster-dialog').close();};
$('#item-count').textContent='LOADING THE GMS V83 ITEM ARCHIVE…';$('#monster-count').textContent='LOADING THE GMS V83 BESTIARY…';loadItems();loadMonsters();if(['items','monsters','exp'].includes(location.hash.slice(1)))$(`[data-tool="${location.hash.slice(1)}"]`).click();
