const $=id=>document.getElementById(id), canvas=$('portrait'),ctx=canvas.getContext('2d');
let catalog,sprite=null,bg='#f9cf4b',serial=0,timer;const cache=new Map();
const scenes={};for(const [key,file] of Object.entries({village:'maple-world.png',victoria:'victoria-island.png',castle:'mushroom-castle.png',tree:'meso-tree.png'})){const im=new Image();scenes[key]=im;im.onload=draw;im.src='assets/'+file;}
function opts(id,items,selected,none=false){$(id).replaceChildren();if(none)$(id).add(new Option('None','0'));for(const a of items)$(id).add(new Option(a.name,a.id));if([...$(id).options].some(o=>o.value==String(selected)))$(id).value=selected;}
function populate(){const gender=+$('gender').value;
 const hair=catalog.hair.filter(x=>Math.floor(x.id/1000)%2===gender && x.id%10===0);
 opts('hair',hair.map(x=>({...x,name:x.name.replace(/^Black /,'')})),gender?31000:30000);
 opts('face',catalog.face.filter(x=>Math.floor(x.id/1000)%2===gender && Math.floor(x.id/100)%10===0),gender?21000:20000);
 for(const k of ['hat','top','bottom','shoes','overall','cape'])opts(k,catalog[k].filter(x=>x.gender===2||x.gender===gender),k==='top'?(gender?1041002:1040002):k==='bottom'?(gender?1061002:1060002):k==='shoes'?1072001:0,k==='hat'||k==='overall'||k==='cape');
 colorOptions();eyeOptions();}
function eyeOptions(){const face=+$('face').value;for(const o of $('eyes').options)o.disabled=!catalog.face.some(x=>x.id===face+100* +o.value);if($('eyes').selectedOptions[0].disabled)$('eyes').value='0';}
function colorOptions(){const h=+$('hair').value;for(const o of $('color').options)o.disabled=!catalog.hair.some(x=>x.id===h+ +o.value);if($('color').selectedOptions[0].disabled)$('color').value='0';}
function draw(){const scene=scenes[bg];const W=1024;ctx.clearRect(0,0,W,W);if(scene&&scene.complete&&scene.naturalWidth){const side=Math.min(scene.width,scene.height);ctx.drawImage(scene,(scene.width-side)/2,(scene.height-side)/2,side,side,0,0,W,W);ctx.fillStyle='#fff9e52b';ctx.fillRect(0,0,W,W);}else{ctx.fillStyle=scene?'#a6d9ed':bg;ctx.fillRect(0,0,W,W);}if(sprite){ctx.imageSmoothingEnabled=false;const scale=(W*+$('zoom').value/100)/Math.max(sprite.width,sprite.height);const w=sprite.width*scale,h=sprite.height*scale;ctx.save();ctx.translate(W/2,W*+$('position').value/100);if($('flip').checked)ctx.scale(-1,1);ctx.drawImage(sprite,-w/2,-h/2,w,h);ctx.restore();}if($('badge').checked){ctx.fillStyle='#214333';ctx.beginPath();ctx.roundRect(350,880,324,94,28);ctx.fill();ctx.fillStyle='#ffdc68';ctx.font='900 54px sans-serif';ctx.textAlign='center';ctx.fillText('$MESO',512,946);}}
function loadImage(url){return new Promise((resolve,reject)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>resolve(im);im.onerror=reject;im.src=url;});}
async function render(){const ticket=++serial;$('download').disabled=true;$('retry').hidden=true;$('status').textContent='Dressing your character…';const skin=+$('skin').value;const ids=[2000+skin,12000+skin,+$('face').value+100* +$('eyes').value,+$('hair').value+ +$('color').value,+$('shoes').value];if(+$('overall').value)ids.push(+$('overall').value);else ids.push(+$('top').value,+$('bottom').value);if(+$('hat').value)ids.push(+$('hat').value);if(+$('cape').value)ids.push(+$('cape').value);
 const items=ids.map(itemId=>JSON.stringify({itemId,region:'GMS',version:'83'})).join(',');const url='https://maplestory.io/api/character/'+encodeURIComponent(items)+'/stand1/0';
 try{const image=cache.get(url)||await Promise.race([loadImage(url),new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),20000))]);if(ticket!==serial)return;cache.set(url,image);sprite=image;draw();$('download').disabled=false;$('status').textContent='Your character is ready. Download a 1024 × 1024 PNG.';}catch(e){if(ticket!==serial)return;$('status').textContent='Could not load this look. Try another option or retry. The renderer needs an internet connection.';$('retry').hidden=false;}}
function schedule(){clearTimeout(timer);$('download').disabled=true;++serial;timer=setTimeout(render,250);}
for(const id of ['gender','skin','hair','color','face','eyes','hat','top','bottom','shoes','overall','cape'])$(id).addEventListener('change',()=>{if(id==='gender')populate();if(id==='hair')colorOptions();if(id==='face')eyeOptions();schedule();});
for(const id of ['zoom','position','badge','flip'])$(id).addEventListener('input',draw);
$('circle').onchange=()=>canvas.classList.toggle('round',$('circle').checked);
for(const b of document.querySelectorAll('[data-bg]'))b.onclick=()=>{bg=b.dataset.bg;document.querySelectorAll('[data-bg]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();};
$('retry').onclick=render;
$('random').onclick=()=>{if(!catalog)return;const pick=id=>{const options=[...$(id).options].filter(o=>!o.disabled);$(id).value=options[Math.floor(Math.random()*options.length)].value;};pick('gender');populate();for(const id of ['skin','hair','face','top','bottom','shoes'])pick(id);colorOptions();eyeOptions();pick('color');pick('eyes');$('hat').value='0';$('overall').value='0';schedule();};
$('reset').onclick=()=>{if(!catalog)return;$('gender').value='0';$('skin').value='0';$('color').value='0';$('eyes').value='0';$('zoom').value='72';$('position').value='50';$('badge').checked=true;$('flip').checked=false;populate();document.querySelector('[data-bg]').click();schedule();};
$('download').onclick=()=>{try{canvas.toBlob(blob=>{if(!blob)throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='my-meso-pfp.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('status').textContent='Downloaded! Your PNG is ready to use as your profile picture.';},'image/png');}catch{$('status').textContent='Download was blocked by the image provider. Please retry.';}};
fetch('catalog.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{catalog=data;populate();render();}).catch(()=>{$('status').textContent='The character catalog could not load. Refresh to try again.';});draw();
